language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
jdk: oraclejdk8
sudo: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master